src/albums/urls.py
from django.urls import path

from . import views


app_name = "albums"

urlpatterns = [
    path("", views.AlbumList.as_view(), name="list"),
    path("categories/", views.categories, name="category_list"),
    path("create/", views.AlbumCreate.as_view(), name="create"),
    path("category/create/", views.create_category, name="category_create"),
    path("category/<slug:slug>/left/", views.move_cat_left, name="category_left"),
    path("category/<slug:slug>/right/", views.move_cat_right, name="category_right",),
    path("category/<slug:slug>/", views.category_detail, name="category_detail"),
    path("category/<slug:slug>/update/", views.category_edit, name="category_edit",),
    path(
        "category/<slug:slug>/delete/", views.category_delete, name="category_delete",
    ),
    path("<int:pk>/", views.AlbumDetail.as_view(), name="detail"),
    path("<int:pk>/left/", views.move_album_left, name="album_left"),
    path("<int:pk>/right/", views.move_album_right, name="album_right"),
    path("<int:pk>/update/", views.AlbumUpdate.as_view(), name="update"),
    path("<int:pk>/delete/", views.AlbumDelete.as_view(), name="delete"),
]

src/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = "core"

urlpatterns = [
    path("", views.home_page, name="home"),
    path(
        "logged_out/",
        TemplateView.as_view(template_name="core/logged_out.html"),
        name="logged_out",
    ),
]

src/django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView


urlpatterns = [
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("not_my_admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("activity/", include("activity.urls")),
    path("members/", include("members.urls")),
    path("albums/", include("albums.urls", namespace="albums")),
    path("invoices/", include("invoices.urls", namespace="invoices")),
    path("products/", include("products.urls", namespace="products")),
    path("", include("core.urls", namespace="core")),
    # re_path(r'^.*', TemplateView.as_view(template_name='core/404.html'), name="404"),
    re_path(
        r"^(?!static) | (?!media).*",
        TemplateView.as_view(template_name="core/404.html"),
        name="404",
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_title = "OHI SHOP"
admin.site.site_header = "OHI SHOP Admin"
admin.site.index_title = "OHI SHOP Models"

src/albums/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from core.models import TimeStampedModel
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class AlbumCategory(MPTTModel, TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, unique=True)
    cat_nr = models.PositiveIntegerField(null=True, blank=True)
    parent = TreeForeignKey(
        "self",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="children",
        db_index=True,
    )
    photo = models.ImageField(
        upload_to="albums/categories/", default="profiles/image-coming-soon.jpg",
    )
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        unique_together = ("parent", "slug")
        verbose_name = "Album Category"
        verbose_name_plural = "Album Categories"

    # def get_slug_list(self):
    #     try:
    #         ancestors = self.get_ancestors(include_self=True)
    #     except:
    #         ancestors = []
    #     else:
    #         ancestors = [i.slug for i in ancestors]
    #     slugs = []
    #     for i in range(len(ancestors)):
    #         slugs.append("/".join(ancestors[: i + 1]))
    #     return slugs

    def get_absolute_url(self):
        return reverse("albums:category_detail", kwargs={"slug": self.slug})

    def _get_unique_slug(self):
        """Changes the slug if 2 or more objects are created with the same title"""
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while AlbumCategory.objects.filter(slug=unique_slug).exists():
            unique_slug = "{}-{}".format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        """Change slug if you change the title"""
        slug = slugify(self.name)
        if self.slug != slug:
            self.slug = slug
            # change the slug if if there's another instance with this slug
            if self.slug:
                self.slug = self._get_unique_slug()
        super(AlbumCategory, self).save()


class Album(TimeStampedModel):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_albums"
    )
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    album_nr = models.PositiveIntegerField(null=True, blank=True)
    categories = models.ForeignKey(
        AlbumCategory, on_delete=models.PROTECT, related_name="albums",
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-created"]

    def get_absolute_url(self):
        return reverse("albums:detail", kwargs={"pk": self.pk})

    def get_first_photo(self):
        img = self.photos.last()
        if img:
            return img.photo.url
        if not img:
            return "/media/profiles/image-coming-soon.jpg"

    def all_photos(self):
        return self.photos.all()


def image_upload_to(instance, filename):
    name = instance.album
    slug = slugify(name)
    basename, file_extension = filename.split(".")
    new_filename = "%s.%s" % (slugify(basename), file_extension)
    return "albums/%s/%s" % (slug, new_filename)


class AlbumPhotos(TimeStampedModel):
    photo = models.ImageField(
        upload_to=image_upload_to, default="profiles/image-coming-soon.jpg"
    )
    album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name="photos")

    def __str__(self):
        return self.photo.name

    class Meta:
        ordering = ["-created"]

src/albums/forms.py
from django import forms
from django.forms import ClearableFileInput, FileInput, Select, TextInput, models
from django.forms.models import inlineformset_factory

from .models import Album, AlbumCategory, AlbumPhotos


class AlbumCategoryCreateForm(models.ModelForm):
    class Meta:
        model = AlbumCategory
        # fields = '__all__'
        exclude = ("slug", "user", "cat_nr", "parent")


class AlbumCategoryUpdateForm(models.ModelForm):
    class Meta:
        model = AlbumCategory
        # fields = '__all__'
        exclude = ("slug", "user", "cat_nr", "parent")
        widgets = {
            "name": TextInput(attrs={"class": "text-field w-input"}),
            # "parent": Select(attrs={"class": "text-field w-input"}),
            # 'photo': TextInput(attrs={'class': 'blu_invoice_edit_field w-input'}),
            # "photo": ClearableFileInput(attrs={"class": "text-field w-input"}),
        }


class AlbumPhotosForm(forms.ModelForm):
    class Meta:
        model = AlbumPhotos
        exclude = ("created", "updated")


AlbumPhotosFormSet = inlineformset_factory(
    Album, AlbumPhotos, form=AlbumPhotosForm, extra=1
)

src/albums/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from activity.utils import create_action

from .forms import AlbumCategoryCreateForm, AlbumCategoryUpdateForm, AlbumPhotosFormSet
from .models import Album, AlbumCategory


@permission_required("albums.add_albumcategory", raise_exception=True)
def create_category(request):
    last_object = AlbumCategory.objects.order_by("-pk").first()
    form = AlbumCategoryCreateForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.cat_nr = 1 if not last_object else int(last_object.cat_nr) + 1
        instance.save()
        create_action(request.user, "created category", instance, instance)
        return redirect("albums:category_list")
    context = {
        "form": form,
    }
    return render(request, "albums/category_create.html", context)


@permission_required("albums.change_albumcategory", raise_exception=True)
def category_edit(request, slug):
    category = get_object_or_404(AlbumCategory, slug=slug)
    if request.method == "POST":
        form = AlbumCategoryUpdateForm(
            instance=category, data=request.POST, files=request.FILES
        )
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            create_action(request.user, "modified category", instance, instance)
            return redirect(category.get_absolute_url())
        else:
            return redirect(category.get_absolute_url())
    else:
        form = AlbumCategoryUpdateForm(instance=category)
    return render(
        request, "albums/category_edit.html", {"form": form, "category": category},
    )


@permission_required("albums.view_albumcategory", raise_exception=True)
def categories(request):
    all_categories = AlbumCategory.objects.order_by("cat_nr")
    return render(request, "albums/category_list.html", {"categories": all_categories})


@permission_required("albums.view_albumcategory", raise_exception=True)
def category_detail(request, slug):
    category = get_object_or_404(AlbumCategory, slug=slug)
    albums = category.albums.prefetch_related("categories").all()

    context = {"object_list": albums, "instance": category}
    return render(request, "albums/category_detail.html", context)


@permission_required("albums.delete_albumcategory", raise_exception=True)
def category_delete(request, slug):
    category = get_object_or_404(AlbumCategory, slug=slug)
    category.delete()
    create_action(request.user, "deleted category", category, category)
    return redirect("albums:category_list")


@permission_required("albums.view_albumcategory", raise_exception=True)
def move_cat_left(request, slug):
    category = get_object_or_404(AlbumCategory, slug=slug)
    current_category = category.cat_nr
    previous_category = (
        AlbumCategory.objects.filter(cat_nr__lt=category.cat_nr)
        .order_by("-cat_nr")
        .first()
    )
    if previous_category is not None:
        # change cat_nr for current category with previous category
        category_new = previous_category.cat_nr
        category.cat_nr = category_new

        # change previous category cat_nr with current category :)
        previous_category.cat_nr = current_category
        # save both category instances
        category.save()
        previous_category.save()
    else:
        pass
    return redirect("albums:category_list")


@permission_required("albums.view_albumcategory", raise_exception=True)
def move_cat_right(request, slug):
    category = get_object_or_404(AlbumCategory, slug=slug)
    current_category = category.cat_nr
    previous_category = (
        AlbumCategory.objects.filter(cat_nr__gt=category.cat_nr)
        .order_by("cat_nr")
        .first()
    )
    if previous_category is not None:
        # change cat_nr for current category with previous category
        category_new = previous_category.cat_nr
        category.cat_nr = category_new

        # change previous category cat_nr with current category :)
        previous_category.cat_nr = current_category
        # save both category instances
        category.save()
        previous_category.save()
    else:
        pass
    return redirect("albums:category_list")


class AlbumList(PermissionRequiredMixin, ListView):
    permission_required = "albums.view_album"
    model = Album
    template_name = "albums/album_list.html"
    paginate_by = 9
    context_object_name = "object_list"

    def get_context_data(self, *args, **kwargs):
        # products = Album.objects.prefetch_related("photos").all()
        albums = Album.objects.select_related("categories").order_by("album_nr")

        page = self.request.GET.get("page", 1)
        paginator = Paginator(albums, 6)
        try:
            objects = paginator.page(page)
        except PageNotAnInteger:
            objects = paginator.page(1)
        except EmptyPage:
            objects = paginator.page(paginator.num_pages)
        index = objects.number - 1
        max_index = len(paginator.page_range)
        start_index = index - 3 if index >= 3 else 0
        end_index = index + 3 if index <= max_index - 3 else max_index
        page_range = paginator.page_range[start_index:end_index]
        context = {"object_list": objects, "page_range": page_range}
        return context


class AlbumCreate(PermissionRequiredMixin, CreateView):
    permission_required = "albums.add_album"
    model = Album
    fields = ["name", "categories", "description"]
    template_name = "albums/album_create_or_update.html"

    def get_context_data(self, **kwargs):
        data = super(AlbumCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            data["photos"] = AlbumPhotosFormSet(self.request.POST, self.request.FILES)
        else:
            data["photos"] = AlbumPhotosFormSet()
        return data

    def form_valid(self, form):
        last_object = Album.objects.order_by("-pk").first()
        context = self.get_context_data()
        photos = context["photos"]
        with transaction.atomic():
            self.object = form.save(commit=False)
            self.object.user = self.request.user
            # if it's first object album_nr 1 else last album_nr + 1
            self.object.album_nr = (
                1 if not last_object else int(last_object.album_nr) + 1
            )
            self.object = form.save()
            if photos.is_valid():
                photos.instance = self.object
                photos.save()
                create_action(
                    self.request.user, "created album", self.object, self.object,
                )
        return super(AlbumCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy("albums:detail", kwargs={"pk": self.object.pk})


class AlbumUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = "albums.change_album"
    model = Album
    fields = ["name", "categories", "description"]
    template_name = "albums/album_create_or_update.html"

    def get_context_data(self, **kwargs):
        data = super(AlbumUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            data["photos"] = AlbumPhotosFormSet(
                self.request.POST, self.request.FILES, instance=self.object
            )
        else:
            data["photos"] = AlbumPhotosFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        photos = context["photos"]
        with transaction.atomic():
            self.object = form.save(commit=False)
            self.object.user = self.request.user
            self.object = form.save()
            if photos.is_valid():
                photos.instance = self.object
                photos.save()
                create_action(
                    self.request.user, "modified album", self.object, self.object,
                )
        return super(AlbumUpdate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy("albums:detail", kwargs={"pk": self.object.pk})


class AlbumDetail(PermissionRequiredMixin, DetailView):
    permission_required = "albums.view_album"
    model = Album
    template_name = "albums/album_detail.html"
    context_object_name = "album"


class AlbumDelete(PermissionRequiredMixin, DeleteView):
    permission_required = "albums.delete_album"
    model = Album
    success_url = reverse_lazy("albums:list")

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.success_url
        self.object.delete()
        create_action(request.user, "deleted album", self.object, self.object)
        return HttpResponseRedirect(success_url)


@permission_required("albums.change_album", raise_exception=True)
def move_album_left(request, pk):
    album = get_object_or_404(Album, pk=pk)
    current_album = album.album_nr
    previous_album = (
        Album.objects.filter(album_nr__lt=album.album_nr).order_by("-album_nr").first()
    )
    if previous_album is not None:
        # change album_nr for current album with previous album
        album_new = previous_album.album_nr
        album.album_nr = album_new

        # change previous album album_nr with current album :)

src/templates/albums/album_confirm_delete.html
{% extends "base.html" %}


{% block content %}

{% include 'core/ohi/ohi_top_nav.html' %}

<div class="main_app_silo">
  <div>
    <form class="form-centered" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
      <h2 class="blulinkheader">Are you sure you want to delete "{{ object }}"?</h2>
      <p><input class="create-object-submit-button" type="submit" value="Confirm"></p>
    </form>
  </div>
  </div>

{% include 'core/ohi/ohi_bottom_nav.html' %}

{% endblock %}

src/templates/albums/album_create_or_update.html
{% extends "base.html" %}
{% load static %}


{% block content %}

{% include 'core/ohi/ohi_top_nav.html' %}
<div class="main_app_silo">
  <h2 class="blulinkheader">Create or Update Album</h2>
  <hr>
    <form class="form-centered" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
      <br/>
        <table align="center">
          {{ photos.management_form }}

          {% for form in photos.forms %}
          {% if forloop.first %}
            <thead class="form-centered">
            <tr>
              {% for field in form.visible_fields %}
                <th>{{ field.label|capfirst }}</th>
              {% endfor %}
            </tr>
            </thead>
            {% endif %}
            <tbody class="form-centered">
              <tr class="{% cycle row1 row2 %} formset_row">
                {% for field in form.visible_fields %}
                  <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                      {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                      {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field }}
                  </td>
                {% endfor %}
              </tr>
            </tbody>
            {% endfor %}
        </table>
      <br/>
      <br/>
      <p><input class="create-object-submit-button" type="submit" value="Save"></p>
    </form>
</div>

{% include 'core/ohi/ohi_bottom_nav.html' %}


<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'ohi-shop/js/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $('.formset_row').formset({
        addText: 'add photo',
        deleteText: 'remove',
        prefix: 'photos'
    });
</script>
{% endblock %}

src/templates/albums/album_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

{% include 'core/ohi/ohi_top_nav.html' %}

<div class="main_app_silo">
{% if album.photos %}
<div class="ohi_photo_detail">
    <div class="ohi_photo_detail_picture">
        <div data-animation="slide" data-duration="500" data-infinite="1" class="w-slider">
            <div class="w-slider-mask">
                {% for obj in album.all_photos %}
                <div class="w-slide"><img src="{{ obj.photo.url }}"/></div>
                {% endfor %}
            </div>
            <div class="w-slider-arrow-left">
                <div class="w-icon-slider-left"></div>
            </div>
            <div class="w-slider-arrow-right">
                <div class="w-icon-slider-right"></div>
            </div>
            <div class="w-slider-nav w-round"></div>
        </div>
<!--        <a href="#" class="ohi_product_detail w-inline-block"></a>-->
    </div>
    <div class="ohi_category_name">{{ album.name }}</div>
    <a href="{% url 'albums:update' pk=album.pk %}" class="ohi_category_button w-button">EDIT</a>
    <a href="{% url 'albums:delete' pk=album.pk %}" class="ohi_category_button delate_button delete w-button">🗑</a>
</div>

{% endif %}
  {% if album.description %}
  <div class="ohi_photo_detail_text">
    <div class="div-block-13">
      <p class="paragraph-4">{{ album.description }}</p>
    </div>
      <a href="{% url 'albums:delete' pk=album.pk %}" class="ohi_category_button w-button">EDIT</a>
  </div>
  {% endif %}
</div>

{% include 'core/ohi/ohi_bottom_nav.html' %}

{% endblock %}

src/templates/albums/album_list.html
{% extends "base.html" %}
{% load static %}


{% block content %}

{% include 'core/ohi/ohi_top_nav.html' %}

<div class="main_app_silo">
{% for album in object_list %}
<div class="ohi_category_box">
  <div class="ohi_cateogry_photo">
    <a href="{{ album.get_absolute_url }}" class="ohi_link_box w-inline-block">
      <img src="{{ album.get_first_photo }}">
    </a>
  </div>
  <div class="ohi_category_name">Album's name: {{ album.name|truncatechars:40 }} {{ album.album_nr }}</div>
  <a href="{% url 'albums:album_left' pk=album.pk %}" class="turn_left_button w-button">&lt;</a>
  <a href="{% url 'albums:album_right' pk=album.pk %}" class="turn_right_button w-button">&gt;</a>
  <a href="{% url 'albums:update' pk=album.pk %}" class="ohi_category_button w-button">EDIT</a>
  <a href="{% url 'albums:delete' pk=album.pk %}" class="ohi_category_button delate_button delete w-button">🗑</a>
</div>
{% endfor %}
<div class="ohi_add_category">
  <a href="{% url 'albums:create' %}" class="ohi_add_categroy w-button">ADD ALBUM</a>
</div>


<!-- Pagination -->
{% include 'core/pagination.html' with object_list=object_list page_range=page_range %}
</div>

{% include 'core/ohi/ohi_bottom_nav.html' %}

{% endblock %}

src/templates/albums/category_create.html
{% extends "base.html" %}
{% load static %}


{% block content %}

{% include 'core/ohi/ohi_top_nav.html' %}

<div class="main_app_silo">
  <h2 class="blulinkheader">Create Category</h2>
  <form class="form-centered" method="post" enctype="multipart/form-data">{% csrf_token %}
      {{ form.as_p }}
      <p><input class="create-object-submit-button" type="submit" value="Submit"></p>
  </form>
</div>

{% include 'core/ohi/ohi_bottom_nav.html' %}

{% endblock %}

src/templates/albums/category_detail.html
{% extends "base.html" %}
{% load static  %}


{% block content %}

{% include 'core/ohi/ohi_top_nav.html' %}

<div class="main_app_silo">
  <div class="ohi_category_box">
    <div class="ohi_cateogry_photo">
        <img src="{{ instance.photo.url }}" alt="{{ instance.title }}">
    </div>
    <div class="ohi_category_name">Category: {{ instance.name }}</div>
    <a href="#" class="turn_left_button w-button">&lt;</a>
    <a href="#" class="turn_right_button w-button">&gt;</a>
    <a href="{% url 'albums:category_edit' slug=instance.slug %}" class="ohi_category_button w-button">EDIT</a>
    <a href="{% url 'albums:category_delete' slug=instance.slug %}" class="ohi_category_button delete w-button">🗑</a>
  </div>

  <hr/>
  {% if object_list %}
  <h4 class="invoice_details_header">Category's Albums</h4>

  {% for object in object_list %}
  <div class="ohi_category_box">
    <div class="ohi_cateogry_photo">
      <a href="{{ object.get_absolute_url }}" class="ohi_link_box w-inline-block">
        <img src="{{ object.get_first_photo }}" alt="{{ object.title }}">
      </a>
    </div>
    <div class="ohi_category_name">Album's name: {{ object.name }}</div>
    <a href="#" class="turn_left_button w-button">&lt;</a>
    <a href="#" class="turn_right_button w-button">&gt;</a>
    <a href="{% url 'albums:update' pk=object.pk %}" class="ohi_category_button w-button">EDIT</a>
    <a href="{% url 'albums:delete' pk=object.pk %}" class="ohi_category_button delete w-button">🗑</a>
  </div>
  {% endfor %}

  {% else %}
  <h4 class="invoice_details_header">There are no albums in this category</h4>
  {% endif %}
</div>
{% include 'core/ohi/ohi_bottom_nav.html' %}

{% endblock %}

src/templates/albums/category_edit.html
{% extends "base.html" %}
{% load static %}


{% block content %}

{% include 'core/ohi/ohi_top_nav.html' %}

<div class="main_app_silo">
  <h2 class="blulinkheader">Update {{ category }}</h2>
  <div class="ohi_category_box_2">
    <div class="ohi_cateogry_photo">
      <img src="{{ category.photo.url }}">
    </div>
  </div>
   <form class="form" method="post" enctype="multipart/form-data">{% csrf_token %}
      {% for field in form %}
      <label class="field-label-4">{{ field.label }}</label>

      {{ field }}
      {{ field.help_text }}
      <input type="submit" value="Submit" class="submit-button w-button">
      {% endfor %}
    </form>
    </div>
  <div>
<!--    <div class="w-form">-->
<!--      <form id="email-form" name="email-form" data-name="Email Form" class="form-3 w-clearfix">-->
<!--        <label for="name" class="field-label-4">Name</label>-->
<!--        <input type="text" class="text-field w-input" maxlength="256" name="name" data-name="Name" id="name">-->
<!--        <input type="submit" value="Submit" data-wait="Please wait..." class="submit-button w-button">-->
<!--      </form>-->


<!--  </div>-->


</div>
{% include 'core/ohi/ohi_bottom_nav.html' %}

{% endblock %}

src/templates/albums/category_list.html
{% extends "base.html" %}
{% load static %}


{% block content %}

{% include 'core/ohi/ohi_top_nav.html' %}



<div class="main_app_silo">
  {% for object in categories %}
  <div class="ohi_category_box">
    {% if object.photo %}
    <div class="ohi_cateogry_photo">
      <a href="{{ object.get_absolute_url }}" class="ohi_link_box w-inline-block">
        <img src="{{ object.photo.url }}" alt="{{ object.title }}">
      </a>
    </div>
    {% endif %}
    <div class="ohi_category_name">Category: {{ object.name }}</div>
    <a href="{% url 'albums:category_left' slug=object.slug %}" class="turn_left_button w-button">&lt;</a>
    <a href="{% url 'albums:category_right' slug=object.slug %}" class="turn_right_button w-button">&gt;</a>
    <a href="{% url 'albums:category_edit' slug=object.slug %}" class="ohi_category_button w-button">EDIT</a>
    <a href="{% url 'albums:category_delete' slug=object.slug %}" class="ohi_category_button delete w-button">🗑</a>
  </div>
  {% endfor %}
  <div class="ohi_add_category">
    <a href="{% url 'albums:category_create' %}" class="ohi_add_categroy w-button">Add category</a>
  </div>
</div>


<!-- Pagination -->
{% include 'core/pagination.html' with categories=object_list page_range=page_range %}

{% include 'core/ohi/ohi_bottom_nav.html' %}


{% endblock %}