src/activity/urls.py
from django.urls import path

from . import views


app_name = "activity"

urlpatterns = [
    path("", views.activity_logs, name="activity_logs"),
]

src/albums/urls.py
from django.urls import path

from . import views


app_name = "albums"

urlpatterns = [
    path("", views.AlbumList.as_view(), name="list"),
    path("categories/", views.categories, name="category_list"),
    path("create/", views.AlbumCreate.as_view(), name="create"),
    path("category/create/", views.create_category, name="category_create"),
    path("category/<slug:slug>/left/", views.move_cat_left, name="category_left"),
    path("category/<slug:slug>/right/", views.move_cat_right, name="category_right",),
    path("category/<slug:slug>/", views.category_detail, name="category_detail"),
    path("category/<slug:slug>/update/", views.category_edit, name="category_edit",),
    path(
        "category/<slug:slug>/delete/", views.category_delete, name="category_delete",
    ),
    path("<int:pk>/", views.AlbumDetail.as_view(), name="detail"),
    path("<int:pk>/left/", views.move_album_left, name="album_left"),
    path("<int:pk>/right/", views.move_album_right, name="album_right"),
    path("<int:pk>/update/", views.AlbumUpdate.as_view(), name="update"),
    path("<int:pk>/delete/", views.AlbumDelete.as_view(), name="delete"),
]

src/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = "core"

urlpatterns = [
    path("", views.home_page, name="home"),
    path(
        "logged_out/",
        TemplateView.as_view(template_name="core/logged_out.html"),
        name="logged_out",
    ),
]

src/django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView


urlpatterns = [
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("not_my_admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("activity/", include("activity.urls")),
    path("members/", include("members.urls")),
    path("albums/", include("albums.urls", namespace="albums")),
    path("invoices/", include("invoices.urls", namespace="invoices")),
    path("products/", include("products.urls", namespace="products")),
    path("", include("core.urls", namespace="core")),
    # re_path(r'^.*', TemplateView.as_view(template_name='core/404.html'), name="404"),
    re_path(
        r"^(?!static) | (?!media).*",
        TemplateView.as_view(template_name="core/404.html"),
        name="404",
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_title = "OHI SHOP"
admin.site.site_header = "OHI SHOP Admin"
admin.site.index_title = "OHI SHOP Models"

src/members/urls.py
from django.urls import path

from . import views


app_name = "members"

urlpatterns = [
    path("", views.all_members, name="member_list"),
    path(
        "<int:pk>/change_password/",
        views.edit_member_password,
        name="edit_member_password",
    ),
    path("<int:pk>/", views.edit_profile, name="member_profile"),
]

src/core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    """
       An abstract base class model that provides self-updating
       ``created`` and ``updated`` fields.
       """

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

src/core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required()
def home_page(request):
    return render(request, "core/home.html")

src/templates/core/ohi/ohi_bottom_nav.html
<div class="base_bottom">
  <p class="paragraph">Copyright Oak Hill Iron 2020</p>
</div>

src/templates/core/ohi/ohi_top_nav.html
<div class="ohi_base_top">
  <div data-collapse="medium" data-animation="default" data-duration="400" class="navbar-3 w-nav">
    <div class="container-3 w-container">
      <a href="{% url 'core:home' %}" class="brand-3 w-nav-brand"></a>
      <nav role="navigation" class="nav-menu-2 w-nav-menu">
        {% if request.user.is_superuser %}
        <a href="{% url 'members:member_list' %}" class="ohi_menu_button w-nav-link">Members</a>
        <a href="{% url 'activity:activity_logs' %}" class="ohi_menu_button w-nav-link">Activity</a>
        {% endif %}
        <a href="{% url 'albums:list' %}" class="ohi_menu_button w-nav-link">Albums</a>
        <a href="{% url 'albums:category_list' %}" class="ohi_menu_button w-nav-link">Categories</a>
      </nav>
      <div class="menu-button w-nav-button">
        <div class="w-icon-nav-menu"></div>
      </div>
    </div>
  </div>
</div>