src/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = "core"

urlpatterns = [
    path("", views.home_page, name="home"),
    path(
        "logged_out/",
        TemplateView.as_view(template_name="core/logged_out.html"),
        name="logged_out",
    ),
]

src/django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView


urlpatterns = [
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("not_my_admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("activity/", include("activity.urls")),
    path("members/", include("members.urls")),
    path("albums/", include("albums.urls", namespace="albums")),
    path("invoices/", include("invoices.urls", namespace="invoices")),
    path("products/", include("products.urls", namespace="products")),
    path("", include("core.urls", namespace="core")),
    # re_path(r'^.*', TemplateView.as_view(template_name='core/404.html'), name="404"),
    re_path(
        r"^(?!static) | (?!media).*",
        TemplateView.as_view(template_name="core/404.html"),
        name="404",
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_title = "OHI SHOP"
admin.site.site_header = "OHI SHOP Admin"
admin.site.index_title = "OHI SHOP Models"

src/products/urls.py
from django.urls import path

from . import views


app_name = "products"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("categories/", views.categories, name="category_list"),
    path(
        "category/<slug:slug>/create-product/",
        views.ProductCreate.as_view(),
        name="product_create",
    ),
    path("category/create/", views.create_category, name="category_create"),
    path("category/<slug:slug>/left/", views.move_cat_left, name="category_left"),
    path("category/<slug:slug>/right/", views.move_cat_right, name="category_right",),
    path(
        "<slug:slug>/update-product/",
        views.ProductUpdate.as_view(),
        name="product_edit",
    ),
    path("<slug:slug>/", views.product_detail, name="product_detail"),
    path(
        "<slug:slug>/<slug:slug2>/delete/", views.product_delete, name="product_delete"
    ),
    path(
        "category/<slug:cat_slug>/<slug:slug>/left/",
        views.move_product_left,
        name="product_left",
    ),
    path(
        "category/<slug:cat_slug>/<slug:slug>/right/",
        views.move_product_right,
        name="product_right",
    ),
    path("category/<slug:slug>/", views.category_detail, name="category_detail"),
    path("category/<slug:slug>/update/", views.category_edit, name="category_edit",),
    path("<slug:slug>/delete/", views.category_delete, name="category_delete",),
]

src/products/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from core.models import TimeStampedModel
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


# from invoices.models import Invoice


class ProductCategory(MPTTModel, TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, unique=True)
    cat_nr = models.PositiveIntegerField(null=True, blank=True)
    parent = TreeForeignKey(
        "self",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="children",
        db_index=True,
    )
    photo = models.ImageField(
        upload_to="products/categories/", default="profiles/image-coming-soon.jpg",
    )
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        unique_together = ("parent", "slug")
        verbose_name = "Product Category"
        verbose_name_plural = "Product Categories"

    # def get_slug_list(self):
    #     try:
    #         ancestors = self.get_ancestors(include_self=True)
    #     except:
    #         ancestors = []
    #     else:
    #         ancestors = [i.slug for i in ancestors]
    #     slugs = []
    #     for i in range(len(ancestors)):
    #         slugs.append("/".join(ancestors[: i + 1]))
    #     return slugs

    def get_absolute_url(self):
        return reverse("products:category_detail", kwargs={"slug": self.slug})

    def _get_unique_slug(self):
        """Changes the slug if 2 or more objects are created with the same name"""
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while ProductCategory.objects.filter(slug=unique_slug).exists():
            unique_slug = "{}-{}".format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        """Change slug if you change the name"""
        slug = slugify(self.name)
        if self.slug != slug:
            self.slug = slug
            # change the slug if if there's another instance with this slug
            if self.slug:
                self.slug = self._get_unique_slug()
        super(ProductCategory, self).save()


class Product(TimeStampedModel):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_products"
    )
    # invoices = models.ManyToManyField(Invoice, blank=True, related_name='products')

    verbose_name = models.CharField(max_length=200)
    sku = models.CharField(max_length=200, blank=True, null=True)
    suggest_retail_price = models.DecimalField(
        blank=True, null=True, max_digits=10, decimal_places=2
    )
    production_cost = models.DecimalField(
        blank=True, null=True, max_digits=10, decimal_places=2
    )
    tier_1_vendor_price = models.DecimalField(
        blank=True, null=True, max_digits=10, decimal_places=2
    )
    tier_2_vendor_price = models.DecimalField(
        blank=True, null=True, max_digits=10, decimal_places=2
    )
    tier_3_vendor_price = models.DecimalField(
        blank=True, null=True, max_digits=10, decimal_places=2
    )
    shipping_weight = models.DecimalField(
        blank=True,
        null=True,
        max_digits=10,
        decimal_places=2,
        verbose_name="shipping weight (lb)",
    )
    shipping_box_length = models.CharField(
        max_length=256, blank=True, null=True, verbose_name="shipping box length (inch)"
    )
    shipping_box_depth = models.CharField(
        max_length=256, blank=True, null=True, verbose_name="shipping box depth (inch)"
    )
    shipping_box_height = models.CharField(
        max_length=256, blank=True, null=True, verbose_name="shipping box height (inch)"
    )
    uline_box = models.CharField(max_length=256, blank=True, null=True)
    product_weight = models.DecimalField(
        blank=True,
        null=True,
        max_digits=10,
        decimal_places=2,
        verbose_name="product weight (lb)",
    )
    product_length = models.DecimalField(
        blank=True,
        null=True,
        max_digits=10,
        decimal_places=2,
        verbose_name="product length (inch)",
    )
    product_depth = models.DecimalField(
        blank=True,
        null=True,
        max_digits=10,
        decimal_places=2,
        verbose_name="product depth (inch)",
    )
    product_height = models.DecimalField(
        blank=True,
        null=True,
        max_digits=10,
        decimal_places=2,
        verbose_name="product height (inch)",
    )

    # photo = ProcessedImageField(upload_to=image_upload_to,
    #                             processors=[ResizeToFit(1000, 1000)],
    #                             format='JPEG',
    #                             options={'quality': 75})
    product_nr = models.PositiveIntegerField(default=1)
    slug = models.SlugField(unique=True)
    categories = models.ForeignKey(
        ProductCategory, on_delete=models.CASCADE, related_name="products",
    )

    def __str__(self):
        return self.verbose_name

    class Meta:
        ordering = ["-created"]

    def get_absolute_url(self):
        return reverse("products:product_detail", kwargs={"slug": self.slug})

    def get_first_photo(self):
        img = self.photos.last()
        if img:
            return img.photo.url
        if not img:
            return "/media/profiles/image-coming-soon.jpg"

    def all_photos(self):
        return self.photos.all()

    def image_tag(self):
        if self.get_first_photo():
            return mark_safe(
                '<img src="%s" style="max-width: 60px; max-height:60px;" />'
                % self.get_first_photo()
            )
        else:
            return "No Image"

    image_tag.short_description = "Photo"

    def get_unique_slug(self):
        """Changes the slug if 2 or more objects are created with the same verbose_name"""
        slug = slugify(self.verbose_name)
        unique_slug = slug
        num = 1
        while Product.objects.filter(slug=unique_slug).exists():
            unique_slug = "{}-{}".format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        """Change slug if you change the verbose_name"""
        slug = slugify(self.verbose_name)
        if self.slug != slug:
            self.slug = slug

            if self.slug:
                self.slug = self.get_unique_slug()
        super(Product, self).save()


def image_upload_to(instance, filename):
    name = instance.product
    slug = slugify(name)
    basename, file_extension = filename.split(".")
    new_filename = "%s.%s" % (slugify(basename), file_extension)
    return "products/%s/%s" % (slug, new_filename)


class ProductPhotos(TimeStampedModel):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="photos"
    )
    photo = models.ImageField(
        upload_to=image_upload_to, default="profiles/image-coming-soon.jpg"
    )

    def __str__(self):
        return self.photo.verbose_name

    class Meta:
        ordering = ["-created"]

src/products/forms.py
from django import forms
from django.forms import FileInput, Select, TextInput, models
from django.forms.models import inlineformset_factory

from .models import Product, ProductCategory, ProductPhotos


class ProductCategoryCreateForm(models.ModelForm):
    class Meta:
        model = ProductCategory
        exclude = ("slug", "user", "cat_nr", "parent")


class ProductCategoryUpdateForm(models.ModelForm):
    class Meta:
        model = ProductCategory
        exclude = ("slug", "user", "cat_nr", "parent")
        widgets = {
            # "name": TextInput(attrs={"class": "text-field w-input"}),
            # "parent": Select(attrs={"class": "text-field w-input"}),
            # 'photo': TextInput(attrs={'class': 'blu_invoice_edit_field w-input'}),
            # "photo": FileInput(attrs={"class": "blu_invoice_edit_field w-input"}),
        }


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ("created", "updated", "categories", "slug", "user")


class ProductPhotosForm(forms.ModelForm):
    class Meta:
        model = ProductPhotos
        exclude = ("created", "updated")


ProductPhotosFormSet = inlineformset_factory(
    Product, ProductPhotos, form=ProductPhotosForm, extra=1
)

src/templates/products/category_detail.html
{% extends "base.html" %}
{% load static  %}


{% block content %}

<div class="blu_top_nav">
  <div data-collapse="medium" data-animation="default" data-duration="400" class="navbar-4 w-nav">
    <div class="container-4 w-container"><a href="{% url 'products:category_list' %}" class="brand-4 w-nav-brand"></a>
      <div style="width: 180px; height: 15px; padding-top: 0px;">
        <a style="text-decoration: none;" href="{% static 'ohi-shop/doc/BLUToolsMasterList_V_03_14.xlsx' %}" download class="w-inline-block">
          <h4 style="margin-top: 5px;" class="heading-12">Download Inventory</h4>
        </a>
      </div>
      <nav role="navigation" class="nav-menu-4 w-nav-menu">
        <a href="{% url 'products:category_list' %}" class="nav-link-11 w-nav-link">Product Categories</a>
        <a href="{{ instance.get_absolute_url }}" class="nav-link-10 w-nav-link">{{ instance }}</a>
      </nav>
      <div class="menu-button-2 w-nav-button">
        <div class="icon-5 w-icon-nav-menu"></div>
      </div>
    </div>
  </div>
</div>

<div class="blu_silo">

  {% if object_list %}

<!--  <h4 class="invoice_details_header">Category's Products</h4>-->
  {% for object in object_list %}
  <div class="blu_catigory product_list category_list">
    <div class="blu_catigory_cover_photo product_list">
      <a href="{{ object.get_absolute_url }}" class="link-block product_list w-inline-block">
        <img class="responsive" src="{{ object.get_first_photo }}" alt="{{ object.verbose_name }}">
      </a>
    </div>
    <div class="blu_catigory_name_txt">{{ object.verbose_name }}‍</div>
      <a href="{% url 'products:product_left' cat_slug=instance.slug slug=object.slug  %}" class="turn_left_button w-button">&lt;</a>
      <a href="{% url 'products:product_right' cat_slug=instance.slug slug=object.slug  %}" class="turn_right_button w-button">&gt;</a>
      <a href="{% url 'products:product_edit' slug=object.slug %}" class="blu_invoice_catigory_edit_button category w-button">Edit</a>
      <a href="{% url 'products:product_delete' slug=object.slug slug2=instance.slug %}" class="blu_invoice_catigory_edit_button delete w-button">🗑</a>
  </div>
  {% endfor %}

  <div class="blu_add_category">
    <a href="{% url 'products:product_create' slug=instance.slug %}" class="blu_category_add_button w-button">Add Product</a>
  </div>

  {% else %}
  <h4 class="invoice_details_header">There are no products in this category</h4>
  <div class="blu_add_category">
    <a href="{% url 'products:product_create' slug=instance.slug %}" class="blu_category_add_button w-button">Add Product</a>
  </div>
  {% endif %}

  <!-- Pagination -->
  {% include 'core/pagination.html' with object_list=object_list page_range=page_range %}
</div>

{% include 'core/blu/blu_bottom_nav.html' %}

{% endblock %}

src/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<div class="blu_top_nav">
  <div data-collapse="medium" data-animation="default" data-duration="400" class="navbar-4 w-nav">
    <div class="container-4 w-container"><a href="{% url 'products:category_list' %}" class="brand-4 w-nav-brand"></a>
      <div style="width: 180px; height: 15px; padding-top: 0px;">
        <a style="text-decoration: none;" href="{% static 'ohi-shop/doc/BLUToolsMasterList_V_03_14.xlsx' %}" download class="w-inline-block">
          <h4 style="margin-top: 5px;" class="heading-12">Download Inventory</h4>
        </a>
      </div>
      <nav role="navigation" class="nav-menu-4 w-nav-menu">
        <a href="{% url 'products:category_list' %}" class="nav-link-11 w-nav-link">Product Categories</a>
        <a href="{{ product.categories.get_absolute_url }}" class="nav-link-10 w-nav-link">{{ product.categories }}</a>
        <a href="{{ product.get_absolute_url }}" class="nav-link-10 w-nav-link">{{ product|truncatechars:30 }}</a>
      </nav>
      <div class="menu-button-2 w-nav-button">
        <div class="icon-5 w-icon-nav-menu"></div>
      </div>
    </div>
  </div>
</div>


<div class="blu_silo product_detail">
  <div class="w-layout-grid grid-3">
    <div class="blu_catigory">
      <div class="blu_catigory_cover_photo">
        <a href="#" class="link-block w-inline-block">
          <div data-animation="slide" data-duration="500" data-infinite="1" class="slider w-slider">
            <div class="mask w-slider-mask">
              {% for obj in product.all_photos %}
                <div class="slide w-slide"><img src="{{ obj.photo.url }}"/></div>
                {% endfor %}
            </div>
            <div class="left-arrow w-slider-arrow-left">
              <div class="w-icon-slider-left"></div>
            </div>
            <div class="right-arrow w-slider-arrow-right">
              <div class="w-icon-slider-right"></div>
            </div>
            <div class="w-slider-nav w-round"></div>
          </div>
        </a>
      </div>
      <div class="blu_catigory_name_txt">{{ product.categories }}</div>
      <a href="{% url 'products:product_edit' slug=product.slug  %}#photos" class="blu_invoice_catigory_edit_button w-button">Edit Photo</a>
    </div>
    </div>
    <div class="div-block-31">
      <div class="div-block-30">
        <h1 class="heading-25">VERBOSE NAME</h1>
        <h1 class="heading-26">{{ product.verbose_name }}</h1>
        <a href="#" id="verbose_name_edit_button" class="button-13 w-button">Edit</a><br/>
        <form class="photo-form" method="post" enctype="multipart/form-data">{% csrf_token %}
          {{ form.verbose_name.non_field_errors }}
          {{ form.verbose_name.errors }}
          {{ form.verbose_name }}
          <p><input id="verbose_name_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
      </div>
      <div class="div-block-30">
        <h1 class="heading-25">SKU</h1>
        <h1 class="heading-26">{{ product.sku }}</h1>
        <a href="#" id="sku_edit_button" class="button-13 w-button">Edit</a><br/>
          {{ form.sku.non_field_errors }}
          {{ form.sku.errors }}
          {{ form.sku }}
        <p><input id="sku_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
      </div>
      <div class="div-block-30">
        <h1 class="heading-25">VENDOR PRICE</h1>
        <h1 class="heading-26">Tier 1: {{ product.tier_1_vendor_price }} Tier 2: {{ product.tier_2_vendor_price }} Tier 3: {{ product.tier_3_vendor_price }}</h1>
        <a href="#" id="tier_1_vendor_price_edit_button" class="button-13 w-button">Edit</a><br/>
        {{ form.tier_1_vendor_price.non_field_errors }}
        {{ form.tier_1_vendor_price.errors }}
        {{ form.tier_1_vendor_price }}
        <p><input id="tier_1_vendor_price_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
        {{ form.tier_2_vendor_price.non_field_errors }}
        {{ form.tier_2_vendor_price.errors }}
        {{ form.tier_2_vendor_price }}
        <p><input id="tier_2_vendor_price_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
        {{ form.tier_3_vendor_price.non_field_errors }}
        {{ form.tier_3_vendor_price.errors }}
        {{ form.tier_3_vendor_price }}
        <p><input id="tier_3_vendor_price_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
      </div>
      <div class="div-block-30">
        <h1 class="heading-25">SUGGEST RETAIL PRICE</h1>
        <h1 class="heading-26">{{ product.suggest_retail_price }}</h1>
        <a href="#" id="suggest_retail_price_edit_button" class="button-13 w-button">Edit</a><br/>
          {{ form.suggest_retail_price.non_field_errors }}
          {{ form.suggest_retail_price.errors }}
          {{ form.suggest_retail_price }}
        <p><input id="suggest_retail_price_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
      </div>
    </div>
    <div id="w-node-56774bf834db-526200e4" class="div-block-30 left">
      <h1 class="heading-25">SHIPPING WEIGHT (lb)</h1>
      <h1 class="heading-26">{{ product.shipping_weight }}</h1>
      <a href="#" id="shipping_weight_edit_button" class="button-13 w-button">Edit</a><br/>
        {{ form.shipping_weight.non_field_errors }}
        {{ form.shipping_weight.errors }}
        {{ form.shipping_weight }}
      <p><input id="shipping_weight_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
    </div>
    <div id="w-node-394d554442c6-526200e4" class="div-block-30">
      <h1 class="heading-25">SHIPPING BOX MEASUREMENTS</h1>
      <h1 class="heading-26">Shipping box length (inch): {{ product.shipping_box_length }}</h1>
      <h1 class="heading-26">Shipping box depth (inch): {{ product.shipping_box_depth }}</h1>
      <h1 class="heading-26">Shipping box height (inch): {{ product.shipping_box_height }}</h1>
      <a href="#" id="shipping_box_length_edit_button" class="button-13 w-button">Edit</a><br/>
      {{ form.shipping_box_length.non_field_errors }}
      {{ form.shipping_box_length.errors }}
      {{ form.shipping_box_length }}
      <p><input id="shipping_box_length_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
      {{ form.shipping_box_depth.non_field_errors }}
      {{ form.shipping_box_depth.errors }}
      {{ form.shipping_box_depth }}
      <p><input id="shipping_box_depth_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
      {{ form.shipping_box_height.non_field_errors }}
      {{ form.shipping_box_height.errors }}
      {{ form.shipping_box_height }}
      <p><input id="shipping_box_height_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
    </div>

  <div class="div-block-30 left">
    <h1 class="heading-25">PRODUCT PRODUCTION COST</h1>
    <h1 class="heading-26">{{ product.production_cost }}</h1>
    <a href="#" id="production_cost_edit_button" class="button-13 w-button">Edit</a><br/>
    {{ form.production_cost.non_field_errors }}
    {{ form.production_cost.errors }}
    {{ form.production_cost }}
    <p><input id="production_cost_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
  </div>
  <div class="div-block-30">
    <h1 class="heading-25">PRODUCT MEASUREMENTS</h1>
    <h1 class="heading-26">Product weight (lb): {{ product.product_weight }}</h1>
    <h1 class="heading-26">Product length (inch): {{ product.product_length }}</h1>
    <h1 class="heading-26">Product depth (inch): {{ product.product_depth }}</h1>
    <h1 class="heading-26">Product height (inch): {{ product.product_height }}</h1>
    <a href="#" id="product_weight_edit_button" class="button-13 w-button">Edit</a><br/>
    {{ form.product_weight.non_field_errors }}
    {{ form.product_weight.errors }}
    {{ form.product_weight }}
    <p><input id="product_weight_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
    {{ form.product_length.non_field_errors }}
    {{ form.product_length.errors }}
    {{ form.product_length }}
    <p><input id="product_length_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
    {{ form.product_depth.non_field_errors }}
    {{ form.product_depth.errors }}
    {{ form.product_depth }}
    <p><input id="product_depth_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
    {{ form.product_height.non_field_errors }}
    {{ form.product_height.errors }}
    {{ form.product_height }}
    <p><input id="product_height_save_button" class="button-13 w-button" type="submit" value="Save changes"></p>
  </div>

  </form>
</div>

{% include 'core/blu/blu_bottom_nav.html' %}

<script src="https://code.jquery.com/jquery-3.3.1.min.js" type="text/javascript" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script type='text/javascript'>
    $(document).ready(function(){
        $('#id_verbose_name').hide();
        $('#verbose_name_save_button').hide();
        $('#verbose_name_edit_button').on('click', function(){
          $('#id_verbose_name').fadeToggle();
          $('#verbose_name_save_button').fadeToggle();
            });

        $('#id_sku').hide();
        $('#sku_save_button').hide();
        $('#sku_edit_button').on('click', function(){
          $('#id_sku').fadeToggle();
          $('#sku_save_button').fadeToggle();
            });

        $('#id_tier_1_vendor_price').hide();
        $('#id_tier_2_vendor_price').hide();
        $('#id_tier_3_vendor_price').hide();
        $('#tier_1_vendor_price_save_button').hide();
        $('#tier_2_vendor_price_save_button').hide();
        $('#tier_3_vendor_price_save_button').hide();
        $('#tier_1_vendor_price_edit_button').on('click', function(){
          $('#id_tier_1_vendor_price').fadeToggle();
          $('#id_tier_2_vendor_price').fadeToggle();
          $('#id_tier_3_vendor_price').fadeToggle();
          $('#tier_1_vendor_price_save_button').fadeToggle();
          $('#tier_2_vendor_price_save_button').fadeToggle();
          $('#tier_3_vendor_price_save_button').fadeToggle();
            });

        $('#id_suggest_retail_price').hide();
        $('#suggest_retail_price_save_button').hide();
        $('#suggest_retail_price_edit_button').on('click', function(){
          $('#id_suggest_retail_price').fadeToggle();
          $('#suggest_retail_price_save_button').fadeToggle();
            });

        $('#id_shipping_weight').hide();
        $('#shipping_weight_save_button').hide();
        $('#shipping_weight_edit_button').on('click', function(){
          $('#id_shipping_weight').fadeToggle();
          $('#shipping_weight_save_button').fadeToggle();
            });

        $('#id_shipping_box_length').hide();
        $('#id_shipping_box_depth').hide();
        $('#id_shipping_box_height').hide();
        $('#shipping_box_length_save_button').hide();
        $('#shipping_box_depth_save_button').hide();
        $('#shipping_box_height_save_button').hide();
        $('#shipping_box_length_edit_button').on('click', function(){
          $('#id_shipping_box_length').fadeToggle();
          $('#id_shipping_box_depth').fadeToggle();
          $('#id_shipping_box_height').fadeToggle();
          $('#shipping_box_length_save_button').fadeToggle();
          $('#shipping_box_depth_save_button').fadeToggle();
          $('#shipping_box_height_save_button').fadeToggle();
            });

        $('#id_product_weight').hide();
        $('#product_weight2_save_button').hide();
        $('#product_weight2_edit_button').on('click', function(){
          $('#id_product_weight').fadeToggle();
          $('#product_weight2_save_button').fadeToggle();
            });

        $('#id_product_weight').hide();
        $('#id_product_length').hide();
        $('#id_product_depth').hide();
        $('#id_product_height').hide();
        $('#product_weight_save_button').hide();
        $('#product_length_save_button').hide();
        $('#product_depth_save_button').hide();
        $('#product_height_save_button').hide();
        $('#product_weight_edit_button').on('click', function(){
          $('#id_product_weight').fadeToggle();
          $('#id_product_length').fadeToggle();
          $('#id_product_depth').fadeToggle();
          $('#id_product_height').fadeToggle();
          $('#product_weight_save_button').fadeToggle();
          $('#product_length_save_button').fadeToggle();
          $('#product_depth_save_button').fadeToggle();
          $('#product_height_save_button').fadeToggle();
            });

        $('#id_production_cost').hide();
        $('#production_cost_save_button').hide();
        $('#production_cost_edit_button').on('click', function(){
          $('#id_production_cost').fadeToggle();
          $('#production_cost_save_button').fadeToggle();
            });

    });
</script>


{% endblock %}