src/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = "core"

urlpatterns = [
    path("", views.home_page, name="home"),
    path(
        "logged_out/",
        TemplateView.as_view(template_name="core/logged_out.html"),
        name="logged_out",
    ),
]

src/django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView


urlpatterns = [
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("not_my_admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("activity/", include("activity.urls")),
    path("members/", include("members.urls")),
    path("albums/", include("albums.urls", namespace="albums")),
    path("invoices/", include("invoices.urls", namespace="invoices")),
    path("products/", include("products.urls", namespace="products")),
    path("", include("core.urls", namespace="core")),
    # re_path(r'^.*', TemplateView.as_view(template_name='core/404.html'), name="404"),
    re_path(
        r"^(?!static) | (?!media).*",
        TemplateView.as_view(template_name="core/404.html"),
        name="404",
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_title = "OHI SHOP"
admin.site.site_header = "OHI SHOP Admin"
admin.site.index_title = "OHI SHOP Models"

src/invoices/urls.py
from django.urls import path

from . import views


app_name = "invoices"

urlpatterns = [
    path("", views.invoice_list, name="invoice_list"),
    path("create/", views.invoice_create, name="invoice_create"),
    path("<slug:slug>/", views.invoice_detail, name="invoice_detail"),
    path("<slug:slug>/update/", views.invoice_update, name="invoice_update"),
    path("<slug:slug>/delete/", views.invoice_delete, name="invoice_delete"),
    path("<int:pk>/pdf/", views.invoice_pdf, name="invoice_pdf"),
    # path("<int:pk>/pdf2/", views.generatepdf, name="generatepdf"),
    path("<int:pk>/left/", views.move_left, name="left"),
    path("<int:pk>/right/", views.move_right, name="right"),
    path("<int:pk>/pdf_download/", views.DownloadPDF.as_view(), name="pdf_download",),
]

src/invoices/forms.py
from django import forms
from django.forms import EmailInput, NumberInput, Textarea, TextInput, models

from .models import Invoice


class InvoiceCreateForm(models.ModelForm):
    class Meta:
        model = Invoice
        exclude = (
            "user",
            "slug",
            "pdf",
            "image",
            "invoice_nr",
            "invoice_number",
        )
        widgets = {
            "visible_notes": Textarea(attrs={"rows": 4, "cols": 15}),
            "private_notes": Textarea(attrs={"rows": 4, "cols": 15}),
        }


class InvoiceUpdateForm(models.ModelForm):
    class Meta:
        model = Invoice
        exclude = (
            "user",
            "slug",
            "pdf",
            "image",
            "invoice_nr",
            "invoice_number",
        )
        labels = {"invoice_title": "", "content": ""}
        widgets = {
            # "invoice_title": TextInput(
            #     attrs={"class": "blu_invoice_edit_field w-input"}
            # ),
            # "invoice_nr": NumberInput(
            #     attrs={"class": "blu_invoice_edit_field w-input"}
            # ),
            # "customer_company_name": TextInput(
            #     attrs={"class": "blu_invoice_edit_field w-input"}
            # ),
            # "customer_name": TextInput(
            #     attrs={"class": "blu_invoice_edit_field w-input"}
            # ),
            # "customer_email": EmailInput(
            #     attrs={"class": "blu_invoice_edit_field w-input"}
            # ),
            # "customer_phone_number": TextInput(
            #     attrs={"class": "blu_invoice_edit_field w-input"}
            # ),
            # "customer_shipping_address": TextInput(
            #     attrs={"class": "blu_invoice_edit_field w-input"}
            # ),
            # "customer_billing_address": TextInput(
            #     attrs={"class": "blu_invoice_edit_field w-input"}
            # ),
            # "line_item_1": TextInput(attrs={"class": "blu_invoice_edit_field w-input"}),
            # "line_item_2": TextInput(attrs={"class": "blu_invoice_edit_field w-input"}),
            # "line_item_3": TextInput(attrs={"class": "blu_invoice_edit_field w-input"}),
            # "line_item_4": TextInput(attrs={"class": "blu_invoice_edit_field w-input"}),
            # "line_item_5": TextInput(attrs={"class": "blu_invoice_edit_field w-input"}),
            # "line_item_6": TextInput(attrs={"class": "blu_invoice_edit_field w-input"}),
            # "line_item_7": TextInput(attrs={"class": "blu_invoice_edit_field w-input"}),
            # "line_item_8": TextInput(attrs={"class": "blu_invoice_edit_field w-input"}),
            # "line_item_9": TextInput(attrs={"class": "blu_invoice_edit_field w-input"}),
            # "line_item_10": TextInput(
            #     attrs={"class": "blu_invoice_edit_field w-input"}
            # ),
            # "shipping_charge": NumberInput(
            #     attrs={"class": "blu_invoice_edit_field w-input"}
            # ),
            # "tax": NumberInput(attrs={"class": "blu_invoice_edit_field w-input"}),
            # "total_due": NumberInput(attrs={"class": "blu_invoice_edit_field w-input"}),
            # "total_paid": NumberInput(
            #     attrs={"class": "blu_invoice_edit_field w-input"}
            # ),
            "visible_notes": Textarea(attrs={"rows": 4, "cols": 15}),
            "private_notes": Textarea(attrs={"rows": 4, "cols": 15}),
        }

src/invoices/views.py
import os
import tempfile
from io import BytesIO

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.files import File
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View

from activity.utils import create_action
from core.helpers import increment_account_number, render_to_pdf
from pdf2image import convert_from_path

from .forms import InvoiceCreateForm, InvoiceUpdateForm
from .models import Invoice


User = get_user_model()


@permission_required("invoices.add_invoice", raise_exception=True)
def invoice_create(request):
    last_object = Invoice.objects.order_by("-pk").first()

    form = InvoiceCreateForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        # first save the invoice object
        instance = form.save(commit=False)
        instance.user = request.user
        # if any objects exists, last_obj.invoice_nr + 1, else invoice_nr 1
        instance.invoice_nr = 1 if not last_object else int(last_object.invoice_nr) + 1
        if last_object is None:
            instance.invoice_number = "BLU-00001"
        else:
            instance.invoice_number = increment_account_number()
        instance.save()

        create_action(request.user, "created invoice", instance, instance)
        # save the pdf field from the object fields
        context = {
            "invoice": instance,
        }
        pdf = render_to_pdf("invoices/invoice.html", context)
        filename = f"Invoice_{instance.slug}.pdf"
        a = instance.pdf.save(filename, File(BytesIO(pdf.content)))
        # print(a)

        # save image from first page of pdf file
        filename = instance.pdf.path
        with tempfile.TemporaryDirectory() as path:
            images_from_path = convert_from_path(
                filename, 100, output_folder=path, last_page=1, first_page=0
            )
        base_filename = os.path.splitext(os.path.basename(filename))[0] + ".jpg"
        save_dir = os.path.join(settings.MEDIA_ROOT, "invoices/images/")
        for page in images_from_path:
            page.save(os.path.join(save_dir, base_filename), "JPEG")

            instance.image = "{}".format(
                os.path.join("invoices/images/", base_filename)
            )
            instance.save()

        return redirect("invoices:invoice_list")

    context = {
        "form": form,
    }
    return render(request, "invoices/invoice_create.html", context)


@permission_required("invoices.view_invoice", raise_exception=True)
def invoice_list(request):
    invoices = Invoice.objects.all().order_by("invoice_nr")

    page = request.GET.get("page", 1)
    paginator = Paginator(invoices, 6)
    try:
        objects = paginator.page(page)
    except PageNotAnInteger:
        objects = paginator.page(1)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)
    index = objects.number - 1
    max_index = len(paginator.page_range)
    start_index = index - 3 if index >= 3 else 0
    end_index = index + 3 if index <= max_index - 3 else max_index
    page_range = paginator.page_range[start_index:end_index]
    context = {"object_list": objects, "page_range": page_range}

    return render(request, "invoices/invoice_list.html", context)


@permission_required("invoices.view_invoice", raise_exception=True)
def invoice_detail(request, slug=None):
    invoice = get_object_or_404(Invoice, slug=slug)
    context = {
        "invoice": invoice,
    }
    return render(request, "invoices/invoice_detail.html", context)


@permission_required("invoices.change_invoice", raise_exception=True)
def invoice_update(request, slug):
    invoice = get_object_or_404(Invoice, slug=slug)
    if request.method == "POST":
        form = InvoiceUpdateForm(
            instance=invoice, data=request.POST, files=request.FILES
        )
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            create_action(request.user, "updated invoice", instance, instance)

            # save the pdf field from the object fields
            context = {
                "invoice": instance,
            }
            pdf = render_to_pdf("invoices/invoice.html", context)
            filename = f"Invoice_{instance.slug}.pdf"
            a = instance.pdf.save(filename, File(BytesIO(pdf.content)))
            # print(a)

            # save image from first page of pdf file
            filename = instance.pdf.path
            with tempfile.TemporaryDirectory() as path:
                images_from_path = convert_from_path(
                    filename, 100, output_folder=path, last_page=1, first_page=0,
                )
            base_filename = os.path.splitext(os.path.basename(filename))[0] + ".jpg"
            save_dir = os.path.join(settings.MEDIA_ROOT, "invoices/images/")
            for page in images_from_path:
                page.save(os.path.join(save_dir, base_filename), "JPEG")

                instance.image = "{}".format(
                    os.path.join("invoices/images/", base_filename)
                )
                instance.save()

            return redirect("invoices:invoice_list")
        else:
            return redirect(invoice.get_absolute_url())
    else:
        form = InvoiceUpdateForm(instance=invoice)
    return render(
        request, "invoices/invoice_update.html", {"form": form, "invoice": invoice},
    )


@permission_required("invoices.delete_invoice", raise_exception=True)
def invoice_delete(request, slug):
    invoice = get_object_or_404(Invoice, slug=slug)
    invoice.delete()
    create_action(request.user, "deleted invoice", invoice, invoice)
    return redirect("invoices:invoice_list")


@permission_required("invoices.view_invoice", raise_exception=True)
def invoice_pdf(request, pk):
    invoice = get_object_or_404(Invoice, pk=pk)
    context = {
        "invoice": invoice,
    }
    pdf = render_to_pdf("invoices/invoice.html", context)
    filename = f"Invoice_{invoice.slug}.pdf"
    if invoice.pdf is None:
        invoice.pdf.save(filename, File(BytesIO(pdf.content)))
    else:
        pass
    return HttpResponse(pdf, content_type="application/pdf")


# @receiver(pre_save, sender=Invoice)
# def generate_obj_pdf(sender, instance, *args, **kwargs):
#     """Saves a pdf file with the data given to the template"""
#     context = {'invoices': instance}
#     pdf = render_to_pdf('invoices/invoice.html', context)
#     filename = f"Invoice_{instance.slug}.pdf"
#     instance.pdf.save(filename, File(BytesIO(pdf.content)))


class DownloadPDF(PermissionRequiredMixin, View):
    permission_required = "invoices.view_invoice"

    def get(self, request, pk, **kwargs):
        invoice = get_object_or_404(Invoice, pk=pk)
        context = {
            "invoice": invoice,
        }
        pdf = render_to_pdf("invoices/invoice.html", context)

        response = HttpResponse(pdf, content_type="application/pdf")
        filename = f"Invoice_{invoice.slug}.pdf"
        content = "attachment; filename='%s'" % filename
        response["Content-Disposition"] = content
        return response


# @login_required
# def generatepdf(request, pk):
#     invoice = get_object_or_404(Invoice, pk=pk)
#     response = HttpResponse(content_type="application/pdf")
#     response['Content-Disposition'] = "inline; filename={date}-{name}-invoices.pdf".format(
#         date=invoice.created.strftime('%Y-%m-%d_%H:%m'),
#         name=slugify(invoice.invoice_title),
#     )
#     html = render_to_string("invoices/invoice_pdf.html", {
#         'invoices': invoice,
#     })
#
#     font_config = FontConfiguration()
#     HTML(string=html).write_pdf(response, font_config=font_config)
#     return response


@permission_required("invoices.change_invoice", raise_exception=True)
def move_left(request, pk):
    invoice = get_object_or_404(Invoice, pk=pk)
    current_invoice = invoice.invoice_nr

    previous_invoice = (
        Invoice.objects.filter(invoice_nr__lt=invoice.invoice_nr)
        .order_by("-invoice_nr")
        .first()
    )
    if previous_invoice is not None:
        # change invoice_nr for current invoice with previous invoice
        invoice_new = previous_invoice.invoice_nr
        invoice.invoice_nr = invoice_new

        # change previous invoice invoice_nr with current invoice :)
        previous_invoice.invoice_nr = current_invoice
        # save both invoice instances
        invoice.save()
        previous_invoice.save()
    else:
        pass
    return redirect("invoices:invoice_list")


@permission_required("invoices.change_invoice", raise_exception=True)
def move_right(request, pk):
    invoice = get_object_or_404(Invoice, pk=pk)
    current_invoice = invoice.invoice_nr

    previous_invoice = (
        Invoice.objects.filter(invoice_nr__gt=invoice.invoice_nr)
        .order_by("invoice_nr")
        .first()
    )
    if previous_invoice is not None:
        # change invoice_nr for current invoice with previous invoice
        invoice_new = previous_invoice.invoice_nr
        invoice.invoice_nr = invoice_new

        # change previous invoice invoice_nr with current invoice :)
        previous_invoice.invoice_nr = current_invoice
        # save both invoice instances
        invoice.save()
        previous_invoice.save()
    else:
        pass
    return redirect("invoices:invoice_list")

src/templates/invoices/invoice.html
{% load static %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>{{ invoice.invoice_title }}</title>
    <style type="text/css">
        @page {
        background-image: url('/static/ohi-shop/images/invoice_background.png');
        background-image: url('{% static "ohi-shop/images/invoice_background.png" %}');
        size: 8.5in 11.0in;
        margin: 0.6cm;
        margin-top: 5cm;
        }
        body {
          font-weight: 200;
          font-size: 14px;
        }
        table {
          width: 100%;
        }
        th {
           /* background-color: #A8A8A8; */
           font-size: 14px;
        }
        th.first, th.second, td.first, td.second {
          text-align: left;
        }
        th.third, th.forth, th.fifth, td.third, td.forth, td.fifth {
          text-align: right;
        }
        td.different-font {
          font-size: 12px;
          font-weight: bold;
        }


        .header {
            font-size: 20px;
            font-weight: 100;
            text-align: center;
            color: #007cae;
        }
        .title {
            font-size: 22px;
            font-weight: 100;
           /* text-align: right;*/
           padding: 10px 20px 0px 20px;
        }
        .title span {
            color: #007cae;
        }
        .details {
            padding: 10px 20px 0px 20px;
            text-align: left !important;
            /*margin-left: 40%;*/
        }
        .hrItem {
            border: none;
            height: 10px;
            /* Set the hr color */
            color: #333; /* old IE */
            background-color: #fff; /* Modern Browsers */
        }
    </style>
  </head>
  <body>
<!--        <div class='wrapper'>-->
<!--            <div class='header'>-->
<!--                <p class='title'>Invoice {{ invoice.invoice_nr }} </p>-->
<!--            </div>-->
<!--        <div>-->
<!--        <div class='details'>-->
<!--            <h1>-->
<!--            {{ invoice.invoice_title }}-->
<!--            </h1>-->
<!--            <hr>-->
<!--            <p>Number: {{ invoice.invoice_nr }}</p>-->
<!--            <p>Customer Company name: {{ invoice.customer_company_name }}</p>-->
<!--            <p>Customer name: {{ invoice.customer_name }}</p>-->
<!--&lt;!&ndash;            <p>Customer email: {{ invoice.customer_email }}</p>&ndash;&gt;-->
<!--&lt;!&ndash;            <p>Customer phone number: {{ invoice.customer_phone_number }}</p>&ndash;&gt;-->
<!--&lt;!&ndash;            <p>Customer shipping address: {{ invoice.customer_shipping_address }}</p>&ndash;&gt;-->
<!--&lt;!&ndash;            <p>Customer billing address: {{ invoice.customer_billing_address }}</p>&ndash;&gt;-->
<!--&lt;!&ndash;            <p>Customer line item 1: {{ invoice.line_item_1 }}</p>&ndash;&gt;-->
<!--            <hr class='hrItem' />-->
<!--        </div>-->

<!--          <table>-->
<!--            <tr>-->
<!--              <td>{{ invoice.invoice_title }}</td>-->
<!--              <td>Number: {{ invoice.invoice_nr }}</td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--              <td>Customer name: {{ invoice.customer_name }}</td>-->
<!--              <td>{{ invoice.customer_email }}</td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--              <td>{{ invoice.customer_phone_number }}</td>-->
<!--              <td>Customer line item 1: {{ invoice.line_item_1 }}</td>-->
<!--            </tr>-->
<!--          </table>-->

<!--    <hr/>-->


    <h2>INVOICE</h2>
    <table class="first">
      <tr>
        <td width="80%">BILL TO</td>
        <td width="10%">INVOICE</td>
        <td width="10%" class="different-font">{{ invoice.invoice_number }}</td>
      </tr>
      <tr>
        <td class="different-font">Progressive Sheet Metal</td>
        <td>DATE</td>
        <td class="different-font">{{ invoice.created|date:'m/d/Y' }}</td>
      </tr>
      <tr>
        <td class="different-font">417 S 7th St</td>
      </tr>
      <tr>
        <td class="different-font">Seward, NE 68434</td>
      </tr>
    </table>
    <br/>
    <br/>
    <br/>
    <br/>

    <table>
    	<tr>
    		<th class="first">SKU</th>
    		<th class="second" width="100%">DESCRIPTION</th>
    		<th class="third">QTY</th>
    		<th class="forth">RATE</th>
        <th class="fifth">AMOUNT</th>
    	</tr>
    	<tr>
        {% for product in invoice.products.all %}
    		<td class="first">{{ product.sku }}</td>
    		<td class="second" width="100%">{{ product.verbose_name }}</td>
    		<td class="third">1</td>
    		<td class="forth">{{ product.suggest_retail_price }}</td>
        <td class="fifth">{{ product.total_due }}</td>
        {% endfor %}
    	</tr>
    	<tr>
    		<td class="first">consultation </td>
    		<td class="second">$225</td>
    		<td class="third">1</td>
        <td class="forth">45.7</td>
    		<td class="fifth">$225</td>
    	</tr>
    	<tr>
    		<td class="first">Service Hours</td>
    		<td class="second">$189</td>
    		<td class="third">45.7</td>
        <td class="forth">45.7</td>
    		<td class="fifth">$8637.30</td>
    	</tr>
    </table>

    <hr>
    <table>
      <tr>
        <td class="third">PAYMENT</td>
        <td class="third">545.00</td>
      </tr>
      <tr>
        <td class="third">BALANCE DUE</td>
        <td class="third"><strong>$0.00</strong></td>
      </tr>
    </table>

    </body>
</html>

src/templates/invoices/invoice_detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}

{% include 'core/blu/blu_top_nav.html' %}

<div class="blu_silo">
  <div class="blu_invoice_detail_render_block_2">
      <div class="blu_invoice_detail_render">
          <img src="{{ invoice.image.url }}" alt="{{ invoice.invoice_title }}">
      </div>
      <a href="{% url 'invoices:invoice_update' slug=invoice.slug %}" class="blu_invoice_catigory_edit_button-copy w-button">Edit</a>
      <a href="{% url 'invoices:invoice_delete' slug=invoice.slug %}" class="blu_invoice_catigory_delete_button blu_invoice_catigory_edit_button w-button">Delete</a>
      <a href="{% url 'invoices:invoice_pdf' pk=invoice.pk %}" class="blu_invoice_catigory_delete_button blu_invoice_catigory_edit_button w-button">PDF</a>
  </div>

  <h4 class="invoice_details_header">Title: {{ invoice.invoice_title }}</h4>
  <h4 class="invoice_details_header">Invoice nr.: {{ invoice.invoice_nr }}</h4>
  <h4 class="invoice_details_header">Customer company name: {{ invoice.customer_company_name }}</h4>
  <h4 class="invoice_details_header">Customer name: {{ invoice.customer_name }}</h4>

  <h4 class="invoice_details_header">Customer email: {{ invoice.customer_email }}</h4>
  <h4 class="invoice_details_header">Customer phone number: {{ invoice.customer_phone_number }}</h4>
  <h4 class="invoice_details_header">Customer shipping address: {{ invoice.customer_shipping_address }}</h4>
  <h4 class="invoice_details_header">Customer billing address: {{ invoice.customer_billing_address }}</h4>

  <h4 class="invoice_details_header">Line item 1: {{ invoice.line_item_1 }}</h4>
  <h4 class="invoice_details_header">Line item 2: {{ invoice.line_item_2 }}</h4>
  <h4 class="invoice_details_header">Line item 3: {{ invoice.line_item_3 }}</h4>
  <h4 class="invoice_details_header">Line item 4: {{ invoice.line_item_4 }}</h4>

  <h4 class="invoice_details_header">Line item 5: {{ invoice.line_item_5 }}</h4>
  <h4 class="invoice_details_header">Line item 6: {{ invoice.line_item_6 }}</h4>
  <h4 class="invoice_details_header">Line item 7: {{ invoice.line_item_7 }}</h4>
  <h4 class="invoice_details_header">Line item 8: {{ invoice.line_item_8 }}</h4>

  <h4 class="invoice_details_header">Line item 9: {{ invoice.line_item_9 }}</h4>
  <h4 class="invoice_details_header">Line item 10: {{ invoice.line_item_10 }}</h4>
  <h4 class="invoice_details_header">Shipping charge: {{ invoice.shipping_charge }}</h4>
  <h4 class="invoice_details_header">Tax: {{ invoice.tax }}</h4>

  <h4 class="invoice_details_header">Total due: {{ invoice.total_due }}</h4>
  <h4 class="invoice_details_header">Total paid: {{ invoice.total_paid }}</h4>
  <p class="invoice_details_header">Visible notes: {{ invoice.visible_notes }}</p>
  <p class="invoice_details_header">Private notes: {{ invoice.private_notes }}</p>
</div>

{% include 'core/blu/blu_bottom_nav.html' %}

{% endblock %}

src/templates/invoices/invoice_list.html
{% extends "base.html" %}
{% load static %}


{% block content %}

{% include 'core/blu/blu_top_nav.html' %}

<div class="blu_silo">
  {% if object_list %}
  {% for invoice in object_list %}
  <div class="blu_invoice_catigory">
    <div class="blu_invoice_catigory_cover_photo">
      <a href="{{ invoice.get_pdf_url }}" class="link-block w-inline-block">
        <img src="{{ invoice.image.url }}">
      </a>
    </div>
    <div class="blu_invoice_catigory_name_txt-copy">
      <h4 class="blu_invoice_category_number">*Invoice# {{ invoice.invoice_nr }}</h4>
      <h5 class="blu_invoice_category_title">*Title of the Invoice<br>{{ invoice.invoice_title|truncatechars:40 }}</h5>
    </div>
    <a href="{% url 'invoices:left' pk=invoice.pk %}" class="turn_left_button w-button">&lt;</a>
    <a href="{% url 'invoices:right' pk=invoice.pk %}" class="turn_right_button w-button">&gt;</a>
    <a href="{% url 'invoices:pdf_download' pk=invoice.pk %}" class="blu_invoice_catigory_edit_button invoice w-button">PDF</a>
    <a href="{% url 'invoices:invoice_update' slug=invoice.slug %}" class="blu_invoice_catigory_edit_button invoice w-button">Edit</a>
    <a href="{% url 'invoices:invoice_delete' slug=invoice.slug %}" class="blu_invoice_catigory_delete_button blu_invoice_catigory_edit_button invoice w-button">🗑</a>
  </div>
  {% endfor %}
  {% endif %}

  <div class="blu_invoice_add_category">
    <a href="{% url 'invoices:invoice_create' %}" class="blu_invoice_category_add_button w-button">Add Invoice</a>
  </div>
<!--  <div class="pagination">-->
<!--    <a href="#" class="button-4 w-button"></a>-->
<!--    <a href="#" class="button-3 w-button"></a>-->
<!--    <a href="#" class="w-button">1</a>-->
<!--    <a href="#" class="w-button">2</a>-->
<!--    <a href="#" class="button-5 w-button"></a>-->
<!--    <a href="#" class="button-6 w-button"></a>-->
<!--  </div>-->
<!--  <div class="blu_invoice_sategory_spacer"></div>-->
</div>


<!-- Pagination -->
{% include 'core/pagination.html' with object_list=object_list page_range=page_range %}

{% include 'core/blu/blu_bottom_nav.html' %}

{% endblock %}

src/templates/invoices/invoice_update.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}


{% block content %}

{% include 'core/blu/blu_top_nav.html' %}

<!--<form class="form" method="post" enctype="multipart/form-data">{% csrf_token %}-->
<!--  {% for field in form %}-->

<!--  <label class="field-label">{{ field.label }}</label>-->
<!--  {{ field }}-->
<!--  {{ field.help_text }}-->
<!--  <input type="submit" value="Submit" class="blu_invoice_edit_field_submit_button w-button">-->
<!--  {% endfor %}-->
<!--</form>-->

<div class="blu_silo">
  <div class="blu_invoice_detail_render_block">
    <div class="blu_invoice_detail_render">
      <img src="{{ invoice.image.url }}">
    </div>
    <a href="#" class="blu_invoice_details_save_button w-button">Save And Render</a>
    <a href="{% url 'invoices:pdf_download' pk=invoice.pk %}" class="blu_invoice_details_download_button w-button">Download Render</a>
  </div>
  <div class="form-block-3 w-clearfix">
    <form id="email-form-2" name="email-form-2" data-name="Email Form 2" class="form-4" method="post" enctype="multipart/form-data">{% csrf_token %}
      {% for field in form %}
      <div class="div-block-33">
        <label class="field-label-5">{{ field.label }}</label>
        {{ field|add_class:"text-field-2 w-input" }}
        {{ field.help_text }}
        <input type="submit" value="Submit" class="button-14 w-button">
      </div>
      {% endfor %}
    </form>
  </div>
</div>






{% include 'core/blu/blu_bottom_nav.html' %}

{% endblock %}